services:
  - type: web
    name: ecommerce-backend
    runtime: node
    rootDir: .
    branch: backend-only
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: "*"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: APP_NAME
        value: Ecommerce
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false
      - key: RESEND_FROM_NAME
        value: Ecommerce
      - key: EMAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
