const ADMIN_ROLES = [
  'super-admin',
  'admin',
  'product-manager',
  'inventory-manager',
  'support',
  'finance-manager',
  'customer-service'
];

const PERMISSIONS = [
  'dashboard:view',
  'admins:manage',
  'roles:assign',
  'system:configure',
  'users:view',
  'users:control',
  'products:view',
  'products:create',
  'products:publish',
  'products:delete',
  'products:manage',
  'categories:manage',
  'inventory:view',
  'inventory:manage',
  'images:upload',
  'orders:view',
  'orders:update',
  'transactions:view',
  'shipments:view',
  'shipments:manage',
  'returns:view',
  'returns:manage',
  'refunds:view',
  'refunds:manage',
  'support:view',
  'support:create',
  'support:respond',
  'support:manage',
  'support:escalate',
  'finance:view',
  'finance:manage',
  'audit:view',
  'settings:view',
  'settings:manage',
  'features:view',
  'features:manage',
  'analytics:view',
  'activity:view',
  'notifications:view',
  'admins:view',
  'notifications:manage',
  'marketing:view',
  'marketing:manage',
];

const DEFAULT_ROLE_PERMISSIONS = {
  'super-admin': PERMISSIONS,
  admin: [
    'dashboard:view',
    'admins:manage',
    'roles:assign',
    'system:configure',
    'users:view',
    'users:control',
    'products:view',
    'products:create',
    'products:publish',
    'products:delete',
    'products:manage',
    'categories:manage',
    'inventory:view',
    'inventory:manage',
    'images:upload',
    'orders:view',
    'orders:update',
    'transactions:view',
    'shipments:view',
    'shipments:manage',
    'returns:view',
    'returns:manage',
    'refunds:view',
    'refunds:manage',
    'support:view',
    'support:respond',
    'support:manage',
    'support:escalate',
    'finance:view',
    'finance:manage',
    'audit:view',
    'settings:view',
    'settings:manage',
    'features:view',
    'features:manage',
    'analytics:view',
    'activity:view',
    'notifications:view',
    'notifications:manage',
    'marketing:view',
    'marketing:manage',
    'admins:view',
  ],
  'product-manager': [
    'dashboard:view',
    'products:view',
    'products:create',
    'products:publish',
    'products:delete',
    'categories:manage',
    'inventory:view',
    'inventory:manage',
    'images:upload',
    'orders:view',
    'transactions:view',
    'analytics:view',
  ],
  'inventory-manager': [
    'dashboard:view',
    'products:view',
    'inventory:view',
    'inventory:manage',
    'orders:view',
    'orders:update',
    'shipments:view',
    'shipments:manage',
    'analytics:view',
  ],
  support: [
    'dashboard:view',
    'users:view',
    'orders:view',
    'support:view',
    'support:respond',
    'activity:view',
  ],
  'finance-manager': [
    'dashboard:view',
    'orders:view',
    'transactions:view',
    'refunds:view',
    'refunds:manage',
    'finance:view',
    'finance:manage',
    'analytics:view',
  ],
  'customer-service': [
    'dashboard:view',
    'users:view',
    'users:control',
    'orders:view',
    'shipments:view',
    'returns:view',
    'refunds:view',
    'support:view',
    'support:create',
    'support:respond',
    'support:manage',
    'activity:view',
  ],
};

const normalizeRole = role =>
  String(role || '')
    .trim()
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/^support-admin$/, 'support');

const normalizePermissions = permissions =>
  Array.from(new Set((permissions || []).filter(permission => PERMISSIONS.includes(permission))));

module.exports = {
  ADMIN_ROLES,
  DEFAULT_ROLE_PERMISSIONS,
  PERMISSIONS,
  normalizePermissions,
  normalizeRole,
};
